stages:
  - build
  - test

#build_test:
#  image: docker:latest
#  services:
#    - docker:dind
#  tags:
#    - meedan
#    - meedan-labs
#  stage: build
#  script:
#    - apk add --no-cache curl jq python py-pip git
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#    - docker build  -f Dockerfile -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"  .
#    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
#  only:
#    - feat/7600-aws-deploy

test:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - meedan
    - meedan-labs
  stage: test
  script:
    - apk add --no-cache curl wget git py-pip
    - pip install docker-compose==1.23.2
    - git clone --recurse-submodules git@github.com:meedan/check.git
    - cd check
    - git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
    - d=configurator/check; for f in $(find $d -type f); do cp "$f" "${f/$d/}"; done
    - docker-compose pull --file docker-test.yml
    - docker-compose up -d --file docker-test.yml

  only:
    - feat/7600-aws-deploy